### ISSUE TITLE
Cellrenderer accessing vue methods

### ISSUE THREAD

**Issue by dpkpnm** [seanlandsman/ag-grid-vue-playground#1]
How do you access vue component methods within cell renderer.

Ex
I have a save button on each row, and save is implemented within the vue component as it needs other data and validation to check before saving. How do you handle this in vue ag-grid cellrenderer.

ag-grid great library!!!

**Comment by seanlandsman** [comment]
Probably way too late now (apologies), but this section of the docs might help: https://www.ag-grid.com/vue-data-grid/component-cell-renderer/#accessing-cell-renderer-instances
